---
- name: Ensure EPEL is installed
  yum: name=epel-release state=present

- name: Ensure JJB is installed
  yum: name={{ item }} state=present
  with_items:
    - python-setuptools
    - python2-jenkins-job-builder

- name: Ensure JJB conf dir exists
  file: dest=/etc/jenkins_jobs state=directory

- name: Copy JJB conf
  template: src=jenkins_jobs.ini.j2 dest=/etc/jenkins_jobs/jenkins_jobs.ini

- name: Copy Job template
  template: src=index.yml.j2  dest={{ ansible_env.HOME }}/index.yml

- name: Push job to jenkins
  shell: jenkins-jobs --ignore-cache update {{ ansible_env.HOME}}/index.yml

- name: Ensure /opt/cccp-service/jenkinsbuilder dir exists on Jenkins master
  file: dest=/opt/cccp-service/jenkinsbuilder state=directory

- name: Get openshift build scripts
  copy:
    src: "{{ item }}"
    dest: /opt/cccp-service/jenkinsbuilder
  with_items:
    - ../jenkinsbuilder/cccp_index_reader.py
    - ../jenkinsbuilder/project-defaults.yml
    - ../jenkinsbuilder/weekly-scan.py
    - ../beanstalk_worker/beanstalkc.py
  when: not vagrant

- name: Replace Jenkins master with its FQDN for Weekly Scan job
  replace: >
      dest=/opt/cccp-service/jenkinsbuilder/weekly-scan.py
      regexp="JENKINS_SLAVE"
      replace='{{ groups['jenkins_slaves'][0] }}'

- name: Replace Beanstalk server with its FQDN for weekly scan job
  replace: >
      dest=/opt/cccp-service/jenkinsbuilder/weekly-scan.py
      regexp="BEANSTALK_SERVER"
      replace='{{ groups['openshift'][0] }}'
