- include: install.yml

- include: config.yml

- name: Restart jenkins
  service: name=jenkins state=restarted
  sudo: yes

- name: Wait for Jenkins to come up
  shell: curl --head --silent http://localhost:8080/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 50
  delay: 10

- include: plugins.yml

- name: restart jenkins
  service: name=jenkins state=restarted enabled=yes

- name: Wait for Jenkins to come up
  shell: curl --head --silent http://localhost:8080/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 50
  delay: 10

- include: jobs.yml
  tags:
    - jenkins
    - jobs

- name: Copy script to monitor access to Jenkins slave from master using Zabbix
  template: src=cron_check_slave_uptime.sh.j2 dest=/root/cron_check_slave_uptime.sh mode=0755
  tags:
    - jenkins
    - monitor

- name: Cronjob to check if Jenkins slave is up, every minute
  cron: name="check jenkins slave access" job="/root/cron_check_slave_uptime.sh"
  tags:
    - jenkins
    - monitor
