---
- name: Install nfs-utils for NFS sharing
  when: test
  sudo: yes
  yum: name=nfs-utils state=present

- name: Create NFS mount directory
  when: test
  sudo: yes
  file:
    path: /srv/pipeline-logs
    state: directory
    mode: 0777

- name: Mount NFS share on the node
  when: test
  sudo: yes
  mount:
    name: /srv/pipeline-logs
    src: "{{ test_nfs_share }}"
    fstype: nfs
    state: mounted
