---
- name: Install nfs-utils for NFS sharing
  when: setup_nfs
  sudo: yes
  yum: name=nfs-utils state=present
  tags:
  - ci_nfs
  - test

- name: Create NFS mount directory
  when: setup_nfs
  sudo: yes
  file:
    path: /nfsshare
    state: directory
    mode: 0777
  tags:
  - ci_nfs
  - test

- name: Add entry in /etc/exports to configure NFS mount
  when: setup_nfs
  sudo: yes
  lineinfile:
    destfile: /etc/exports
    line: "/nfsshare (rw,sync,no_subtree_check,all_squash,anonuid=0,anongid=0)"
  tags:
  - ci_nfs
  - test

- name: Start and Enable NFS service
  when: setup_nfs
  sudo: yes
  service: name=nfs-server enabled=yes state=started
  tags:
  - ci_nfs
  - test
