---
- name: Install nfs-utils for NFS sharing
  when: setup_nfs
  sudo: yes
  yum: name=nfs-utils state=present
  tags:
  - ci_nfs
  - test

- name: Install firewalld for opening NFS ports
  when: setup_nfs
  sudo: yes
  yum: name=firewalld state=present
  tags:
  - ci_nfs
  - test

- name: Start firewalld service
  when: setup_nfs
  sudo: yes
  service: name=firewalld enabled=yes state=started
  tags:
  - ci_nfs
  - test

- name: Create NFS mount directory
  when: setup_nfs
  sudo: yes
  file:
    path: /nfsshare
    state: directory
    mode: 0777
  tags:
  - ci_nfs
  - test

- name: Add entry in /etc/exports to configure NFS mount
  when: setup_nfs
  sudo: yes
  lineinfile:
    destfile: /etc/exports
    line: "/nfsshare (rw,sync,no_subtree_check,all_squash,anonuid=0,anongid=0)"
  tags:
  - ci_nfs
  - test

- name: ensure iptables is configured to allow TCP ports 2049
  when: setup_nfs
  sudo: yes
  firewalld: port=2049/tcp zone=public permanent=true state=enabled immediate=yes
  tags:
  - ci_nfs
  - test

- name: Ensure iptables is configured to allow TCP ports 111
  when: setup_nfs
  sudo: yes
  firewalld: port=111/tcp zone=public permanent=true state=enabled immediate=yes
  tags:
  - ci_nfs
  - test

- name: Start and Enable NFS service
  when: setup_nfs
  sudo: yes
  service: name=nfs-server enabled=yes state=started
  tags:
  - ci_nfs
  - test
