---
- name: Stop and remove mail-server container
  sudo: yes
  docker_contianer:
    name: mail-server
    state: absent
    force_kill: yes

- name: Stop and remove OpenShift origin container
  sudo: yes
  docker_contianer:
    name: origin
    state: absent
    force_kill: yes

- name: Remove exited containers
  sudo: yes
  ignore_erros: yes
  shell: docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs docker rm

- name: Remove all images
  sudo: yes
  shell: docker rmi -f `docker images -a -q`
  ignore_errors: yes

- name: Remove mounts
  sudo: yes
  shell: for f in `mount | grep origin | cut -f3 -d\ `; do umount $f ; done
  ignore_errors: yes

- name: Remove /var/lib/origin/* directory contents
  sudo: yes
  shell: rm -rf /var/lib/origin/*
