---

- name: Ensure java is not installed
  yum: name=java state=absent
  tags:
  - jenkins
  - jenkins/master
  - jenkins/slave
  - config

- name: install deps on jenkins nodes
  yum: name={{ item }} state=present
  with_items:
   - java-1.7.0-openjdk
   - git
  tags:
  - jenkins
  - jenkins/master
  - jenkins/slave
  - config
