---

- name: Ensure log path exists
  file: path=/srv/pipeline-logs/cccp.log state=touch

- name: Stop mail-server container
  sudo: yes
  ignore_errors: true
  docker_container:
    name: mail-server
    state: absent
    force_kill: true

- name: Set log level
  replace: >
      dest="{{ ansible_env.HOME }}/cccp-service/mail_service/config.py"
      regexp="LOG_LEVEL =.*"
      replace="LOG_LEVEL = '{{ log_level }}'"

- name: Build mail-server container image
  sudo: yes
  docker_image:
    name: mail-server
    path: "{{ ansible_env.HOME }}/cccp-service/mail_service"
    dockerfile: Dockerfile.mailserv

- name: Start Mail Service
  docker_container:
      name: mail-server
      state: started
      image: mail-server
      restart_policy: unless-stopped
      volumes:
        /srv/pipeline-logs:/srv/pipeline-logs:rw
      env:
        DEPLOYMENT: "{{deployment}}"
