---
- name: Stop Mail Service
  shell: docker rm -f mail-server
  register: result
  until: result['rc'] == 0 or result['stderr'].find('No such container') >= 0
  retries: 10
  delay: 10
  ignore_errors: true

- name: Print result
  debug: msg="Result= {{ result }}"

- name: Build mail server image
  shell: docker build -t mail-server -f ./Dockerfile.mailserv .
  args:
      chdir: "{{ ansible_env.HOME }}/cccp-service/mail_service"

- name: Start Mail Service
  docker:
      name: mail-server
      state: started
      image: mail-server
      restart_policy: unless-stopped
