---
- name: Stop and remove {{ item }} container
  sudo: yes
  docker_container:
    name: "{{ item }}"
    state: absent
    force_kill: yes
  with_items:
    - dispatcher-worker
    - build-worker
    - test-worker
    - delivery-worker
