---
- name: Stop and remove worker containers
  sudo: yes
  docker_container:
    name: "{{ item }}"
    state: absent
    force_kill: yes
  with_items:
    - dispatcher-worker
    - build-worker
    - test-worker
    - delivery-worker

- name: Remove /opt/cccp-service directory
  sudo: yes
  file: path=/opt/cccp-service state=absent
