---
- name: Enable epel repo
  yum: name=epel-release state=installed

- name: Install docker py
  yum: name={{item}} state=installed
  with_items:
    - docker
    - python-docker-py

#Push ca cert to slave for worker
- name: Ensure /opt/cccp-service/beanstalk_worker dir exists on Jenkins slaves
  file: dest=/opt/cccp-service/beanstalk_worker state=directory

- name: Push oc files to Jenkins slaves
  synchronize:
    mode: push
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    rsync_opts:
        - "{{ rsync_ssh_opts }}"
  with_items:
    - {src: /tmp/oc_ca.crt, dest: /opt/cccp-service/beanstalk_worker/ca.crt}

- name: Get openshift build scripts
  get_url:
    url: "{{ item }}"
    dest: /opt/cccp-service/beanstalk_worker
    mode: u+x
  with_items:
    - https://raw.githubusercontent.com/CentOS/container-pipeline-service/master/beanstalk_worker/beanstalkc.py
    - https://raw.githubusercontent.com/CentOS/container-pipeline-service/master/beanstalk_worker/worker_start_build.py
    - https://raw.githubusercontent.com/CentOS/container-pipeline-service/master/beanstalk_worker/DependencyChecker.py
    - https://raw.githubusercontent.com/CentOS/container-pipeline-service/master/beanstalk_worker/worker_start_test.py
    - https://raw.githubusercontent.com/CentOS/container-pipeline-service/master/beanstalk_worker/worker_dispatcher.py
    - https://raw.githubusercontent.com/CentOS/container-pipeline-service/master/beanstalk_worker/worker_start_delivery.py

- name: Get service files for workers
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "https://raw.githubusercontent.com/centos/container-pipeline-service/master/beanstalk_worker/cccp-build-worker.service", dest: /etc/systemd/system/cccp-build-worker.service}
    - {src: "https://raw.githubusercontent.com/centos/container-pipeline-service/master/beanstalk_worker/cccp-test-worker.service", dest: /etc/systemd/system/cccp-test-worker.service}
    - {src: "https://raw.githubusercontent.com/centos/container-pipeline-service/master/beanstalk_worker/cccp-delivery-worker.service", dest: /etc/systemd/system/cccp-delivery-worker.service}
    - {src: "https://raw.githubusercontent.com/centos/container-pipeline-service/master/beanstalk_worker/cccp-dispatcher-worker.service", dest: /etc/systemd/system/cccp-dispatcher-worker.service}

